version: 0.2

env:
  variables:
    HADS_DEBUG: "true"
    HADS_USE_MOCK: "false"
    HADS_NO_AUTH: "false"
    HADS_DENY_SIGNUP: "true"
    HADS_DENY_LOGIN: "false"

phases:
  install:
    runtime-versions:
      python: 3.13
  build:
    commands:
      - aws s3 sync static/ s3://hakira0627-sgp-main/CloudFront/static --delete
      - aws s3 cp favicon/favicon.ico s3://hakira0627-sgp-main/CloudFront/favicon.ico
      - sam build
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides ParameterKey=DEBUG,ParameterValue=$HADS_DEBUG ParameterKey=UseMock,ParameterValue=$HADS_USE_MOCK ParameterKey=NoAuth,ParameterValue=$HADS_NO_AUTH ParameterKey=DenySignup,ParameterValue=$HADS_DENY_SIGNUP ParameterKey=DenyLogin,ParameterValue=$HADS_DENY_LOGIN
