version: 0.2

env:
  variables:
    HADS_DEBUG: "true"
    HADS_USE_MOCK: "false"
    HADS_NO_AUTH: "false"

phases:
  install:
    runtime-versions:
      python: 3.13
  build:
    commands:
      - aws s3 sync static/ s3://hakira0627-sgp-main/CloudFront/static --delete
      - aws s3 cp favicon/favicon.ico s3://hakira0627-sgp-main/CloudFront/favicon.ico
      - sam build
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides DEBUG=$HADS_DEBUG USE_MOCK=$HADS_USE_MOCK NO_AUTH=$HADS_NO_AUTH
