version: 0.2

env:
  parameter-store:
    WAMBDA_DEBUG: /wambda/debug
    WAMBDA_USE_MOCK: /wambda/use_mock
    WAMBDA_NO_AUTH: /wambda/no_auth
    WAMBDA_DENY_SIGNUP: /wambda/deny_signup
    WAMBDA_DENY_LOGIN: /wambda/deny_login
    WAMBDA_LOG_LEVEL: /wambda/log_level
  variables:
    S3_BUCKET: "hakira0627-sgp-pro-main"
    DYNAMODB_TABLE: "table-sgp-pro-main"
    SQS_QUEUE_NAME: "sqs-sgp-analysis.fifo"

phases:
  install:
    runtime-versions:
      python: 3.13
  build:
    commands:
      - aws s3 sync static/ s3://$S3_BUCKET/CloudFront/static --delete
      - aws s3 cp favicon/favicon.ico s3://$S3_BUCKET/CloudFront/favicon.ico
      - sam build
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides ParameterKey=DEBUG,ParameterValue=$WAMBDA_DEBUG ParameterKey=UseMock,ParameterValue=$WAMBDA_USE_MOCK ParameterKey=NoAuth,ParameterValue=$WAMBDA_NO_AUTH ParameterKey=DenySignup,ParameterValue=$WAMBDA_DENY_SIGNUP ParameterKey=DenyLogin,ParameterValue=$WAMBDA_DENY_LOGIN ParameterKey=LogLevel,ParameterValue=$WAMBDA_LOG_LEVEL ParameterKey=DynamoDBTable,ParameterValue=$DYNAMODB_TABLE ParameterKey=SQSQueueName,ParameterValue=$SQS_QUEUE_NAME
